import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./styles/globals.css";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Semai",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} min-h-dvh antialiased bg-white text-slate-900}`}>
        {children}
      </body>
    </html>
  );
}
